@baseUrl = http://localhost:3001

###
# @name generateToken
# simulate token generation (mocked
GET {{baseUrl}}/auth/fake-token 

//health endpoint
###
# @name hearbeat
GET {{baseUrl}}


